version: '3.1'
services:
  postgresv2:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: fast-question
    image: fast-question
    build: ./
    ports:
      - "8080:8080"